" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

let MRU_File = '.vim/vim_mru_files'
set runtimepath+=~/.vim/vim_runtime
set viminfo+=n~/.vim/viminfo
set rtp+=/usr/local/opt/fzf

source ~/.vim/vim_runtime/vimrcs/basic.vim
source ~/.vim/vim_runtime/vimrcs/filetypes.vim
source ~/.vim/vim_runtime/vimrcs/plugins_config.vim
source ~/.vim/vim_runtime/vimrcs/extended.vim
try
  source ~/.vim/vim_runtime/my_configs.vim
catch
endtry
